### ISSUE TITLE
目前已经出现了更大的 av 号 （大于 int32 范围），现有的算法已再次失效

### ISSUE THREAD

**Issue by Eyre-S** [outloudvi/tg-antibv-bot#5]
这两天被人发现已经有大于 int32 范围的 av 号出现：

https://www.bilibili.com/video/av111298867365120/

`av111298867365120` = `BV1L9Uoa9EUx`

目前 antibvbot 还不支持这么大的数值：

![image](https://github.com/outloudvi/tg-antibv-bot/assets/31265413/10599214-108c-4adf-bd91-3cc33ea84f3b)

在 [bvid说明 | BAC Document](https://socialsisteryi.github.io/bilibili-API-collect/docs/misc/bvid_desc.html) 里面有一个新算法可以使用，目前也已经测试针对上面的 avid/bvid 有效。

**Comment by outloudvi** [comment]
感谢报告。已经更新为新算法。
